language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: ZfRFdz2/deK8y8wpu+t+PfJwCjOzeGefUWBslianP9HAZSTBjEcDoFEREWzTEmTaifTEgeKrVhG6EVYQjT29bdENKVs0LByFGuYnz6z4AzPeEYqTdn3sWZyPQX+aZ1UMZwbmM+Gv6zM3nCcJykDTveKc/Pz7NORanPqvJDoWFj8JUUqz8Is+FeoGP7h+7XusE1EisnHD01UxoROvhnpPhtTJdkVGblM4yf1epobTAD9J069yPu842FmmgsCoSIdVtVwlICODN9PUt6idIjUZWcJUGYcRRcZo6hRuNriawrL9uUKC/EYerrVI0/9Nj4O3H/B/cywqykeJTzaVGf1rPJIqZQ+2Vbf8Vw27mkVsE+AlS2xstuoQOkF+8FAbxAZrMu+J05AsuFEgk0DIy1Gr0eoSss4F1Xxcca307N71iXII5Xqf4TWWsNES+VlpWZ/pzX7LbogNk2fVirPPGkAC+Ano4nM1PHIRPO+2A+uiKXYZa+wFscySlmd6ybmnF8hRCi/ZE1Fkp0kpeNdA0F3od0uA/PnD0l/qtBPmVSiPwAFlWTG3e4xeaOPsaLDVLPxMA9pZzv681V0bcndRrOMX42YVrBzM7w0cGckgoLOKIF07zIPbPK8Ux4JJNHT/8Cdy42MrBmQiSMq50Q13GzprAZuRhNN8+O1rjkoWnUBwqv4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: ws50jJF0U5Ay3mAPIQAko0T3B4jrep5GmFCdpiFe0uNZvEAV9WKq8oS0MVR9uFLgS+rR/0MynbdDu7s6O76XYghJ84qsGGFWDXKKqLDEFGOpTOwlfrhJK0zLuMg/t/PT7JoyeNzIIJos2GZuTWFLfFn5pBQdFCeyG+0xRsmwSiyKRbJIch8xBTouif/jngcmbst+y9VOt4YiJ6bpG3RXM39yZw2RMT8nCFl2F3LqLNnMRJsOrF4kboYLH3bZp8EZnUirpzNWKM89w0wuEhXM0oEx05wGsNVLwcRVrYlWV8tOFzKWWr2aNlVKdi2lOjkJKYPoleV7oHe1+oAE5+mFlTCw7SmZ51bcsZRyThE1tx5T4hWXHfBJrajnnr9Q4mERcRKj0v7+yfY6g/OmV2EFne/vOFtX2u1oZIhuBhEee0fQicx8jKYO4lPXyDocyr+EX4b5oPd33YZcEelv4ctutOncZth7YexWPLSe9m5gdgtzd+7EfM1ZDTTPfHspco5pDcecQn0ew+1+ZQ/YQOGsEyBJBdjowuZkyQNKtmpQKexDu1Pj6Dw3Y075Ke2iNolxfBkT1EUwtaXkWvxEcDKEPfvDrGV9k8KKkJgYvNbwZZaeP/UN5uVCWDqBuu7E76ECxgwUkXqGeNgNRcJuB6dbf2ntm2snzRwsXnXqm84PEpM=
sudo: false
